# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135hz26wydzIqZNewbheeYPh_Q1v2BEOV
"""

# import numpy as np
#
# def compute_T(theta, alpha, d, a):
#     mat = np.array([[ np.cos(theta), -np.sin(theta)*np.cos(alpha), np.sin(theta)*np.sin(alpha), a*np.cos(theta)],
#                     [ np.sin(theta),  np.cos(theta)*np.cos(alpha), -np.cos(theta)*np.sin(alpha), a*np.sin(theta)],
#                     [ 0,              np.sin(alpha),                np.cos(alpha),              d],
#                     [ 0,              0,             0, 1]])
#     return mat
#
# def skew(w):
#   res = np.array([
#             [0, -w[2], w[1]],
#             [w[2], 0, -w[0]],
#             [-w[1], w[0], 0]])
#
#   return res
#
# def (q_in):
#
#     J = np.zeros((6, 7))
#
#     ## STUDENT CODE GOES HERE
# 	  #x direction offsets
#     x1 = 0
#     x2 = 0
#     x3 = 0.0825
#     x4 = -0.0825
#     x5 = 0
#     x6 = 0.088
#     x7 = 0
#
#     #z direction offsets
#     z0 = .141 #world to base offset
#     z1 = 0.333
#     z2 = 0
#     z3 = 0.316
#     z4 = 0
#     z5 = 0.384
#     z6 = 0
#     z7 = 0.210
#
#     #joint angles
#     q1 = q_in[0]
#     q2 = q_in[1]
#     q3 = q_in[2]
#     q4 = q_in[3]
#     q5 = q_in[4]
#     q6 = q_in[5]
#     q7 = q_in[6] - np.pi/4
#
#
#
#     params = np.array([
#     [0, -np.pi/2, z1, q1],
#     [0, np.pi/2, 0, q2],
#     [x3, np.pi/2, z3, q3],
#     [x4, -np.pi/2, 0, q4],
#     [0, np.pi/2, z5, q5],
#     [x6, np.pi/2, 0, q6],
#     [0, 0, z7, q7]])
#     ##compute_A(theta, alpha, d, a)
#
#     T01 = compute_T(params[0][0], params[0][1], params[0][2], params[0][3])
#     T12 = compute_T(params[1][0], params[1][1], params[1][2], params[1][3])
#     T23 = compute_T(params[2][0], params[2][1], params[2][2], params[2][3])
#     T34 = compute_T(params[3][0], params[3][1], params[3][2], params[3][3])
#     T45 = compute_T(params[4][0], params[4][1], params[4][2], params[4][3])
#     T56 = compute_T(params[5][0], params[5][1], params[5][2], params[5][3])
#     T67 = compute_T(params[6][0], params[6][1], params[6][2], params[6][3])
#
#
#     T00 = np.array([	[1, 0, 0, 0],
# 			[0, 1, 0, 0],
# 			[0, 0, 1, .141],
# 			[0, 0, 0, 1]	])
#     T01 = T01
#     T02 = T01 @ T12
#     T03 = T01 @ T12 @ T23
#     T04 = T01 @ T12 @ T23 @ T34
#     T05 = T01 @ T12 @ T23 @ T34 @ T45
#     T06 = T01 @ T12 @ T23 @ T34 @ T45 @ T56
#     T07 = T01 @ T12 @ T23 @ T34 @ T45 @ T56 @ T67
#
#     p0e = T07[:3,3]
#     print("shape should be 8x3", p0e.shape)
#     # p0e = x[7,:] = np.transpose( T0e[range(4),3] )
#     # jointPositions = x[:,0:3]
#
#     jointPositions = np.array([T00[:3,3], T01[:3,3], T02[:3,3], T03[:3,3], T04[:3,3], T05[:3,3], T06[:3,3], T07[:3,3]])
#
#     return jointPositions
#
#





import numpy as np
from math import pi, acos
from scipy.linalg import null_space
from copy import deepcopy

from lib.calcJacobian import calcJacobian
from lib.detectCollision import detectCollision
from lib.loadmap import loadmap

# from calcJacobian import calcJacobian
from lib.calculateFK import FK
# from detectCollision import detectCollision
# from loadmap import loadmap


class PotentialFieldPlanner:

    # JOINT LIMITS
    lower = np.array([-2.8973,-1.7628,-2.8973,-3.0718,-2.8973,-0.0175,-2.8973])
    upper = np.array([2.8973,1.7628,2.8973,-0.0698,2.8973,3.7525,2.8973])

    center = lower + (upper - lower) / 2 # compute middle of range of motion of each joint
    fk = FK()

    def __init__(self, tol=1e-4, max_steps=500, min_step_size=1e-5):
        """
        Constructs a potential field planner with solver parameters.

        PARAMETERS:
        tol - the maximum distance between two joint sets
        max_steps - number of iterations before the algorithm must terminate
        min_step_size - the minimum step size before concluding that the
        optimizer has converged
        """

        # YOU MAY NEED TO CHANGE THESE PARAMETERS

        # solver parameters
        self.tol = tol
        self.max_steps = max_steps
        self.min_step_size = min_step_size


    ######################
    ## Helper Functions ##
    ######################
    # The following functions are provided to you to help you to better structure your code
    # You don't necessarily have to use them. You can also edit them to fit your own situation

    @staticmethod
    def attractive_force(target, current):
        """
        Helper function for computing the attactive force between the current position and
        the target position for one joint. Computes the attractive force vector between the
        target joint position and the current joint position

        INPUTS:
        target - 3x1 numpy array representing the desired joint position in the world frame
        current - 3x1 numpy array representing the current joint position in the world frame

        OUTPUTS:
        att_f - 3x1 numpy array representing the force vector that pulls the joint
        from the current position to the target position
        """

        ## STUDENT CODE STARTS HERE

        att_f = np.zeros((3, 1))
        att_field_strength = .1
        threshold = .1

        parabolic = -att_field_strength * (current - target)
        conic = -(current - target) / np.linalg.norm([current, target])

        dist = np.linalg.norm([current, target])

        if dist > threshold: #far from goal, use conic
          return conic
        else:
          return parabolic


        ## END STUDENT CODE

        return att_f

    @staticmethod
    def repulsive_force(obstacle, current, unitvec=np.zeros((3,1))):
        """
        Helper function for computing the repulsive force between the current position
        of one joint and one obstacle. Computes the repulsive force vector between the
        obstacle and the current joint position

        INPUTS:
        obstacle - 1x6 numpy array representing the an obstacle box in the world frame
        current - 3x1 numpy array representing the current joint position in the world frame
        unitvec - 3x1 numpy array representing the unit vector from the current joint position
        to the closest point on the obstacle box

        OUTPUTS:
        rep_f - 3x1 numpy array representing the force vector that pushes the joint
        from the obstacle
        """

        ## STUDENT CODE STARTS HERE

        rep_f = np.zeros((3, 1))
        p0 = .1

        rep_field_strength = .1
        dist, unit = PotentialFieldPlanner.dist_point2box(current.reshape(1,3), obstacle)
        if dist[0] > p0:
          return rep_f
        else:
          return rep_field_strength * (1/dist - 1/p0) * 1/(dist**2) * unit

        ## END STUDENT CODE

        return rep_f

    @staticmethod
    def dist_point2box(p, box):
        """
        Helper function for the computation of repulsive forces. Computes the closest point
        on the box to a given point

        INPUTS:
        p - nx3 numpy array of points [x,y,z]
        box - 1x6 numpy array of minimum and maximum points of box

        OUTPUTS:
        dist - nx1 numpy array of distance between the points and the box
                dist > 0 point outside
                dist = 0 point is on or inside box
        unit - nx3 numpy array where each row is the corresponding unit vector
        from the point to the closest spot on the box
            norm(unit) = 1 point is outside the box
            norm(unit)= 0 point is on/inside the box

         Method from MultiRRomero
         @ https://stackoverflow.com/questions/5254838/
         calculating-distance-between-a-point-and-a-rectangular-box-nearest-point
        """
        # THIS FUNCTION HAS BEEN FULLY IMPLEMENTED FOR YOU

        # Get box info
        boxMin = np.array([box[0], box[1], box[2]])
        boxMax = np.array([box[3], box[4], box[5]])
        boxCenter = boxMin*0.5 + boxMax*0.5
        p = np.array(p)

        # Get distance info from point to box boundary
        dx = np.amax(np.vstack([boxMin[0] - p[:, 0], p[:, 0] - boxMax[0], np.zeros(p[:, 0].shape)]).T, 1)
        dy = np.amax(np.vstack([boxMin[1] - p[:, 1], p[:, 1] - boxMax[1], np.zeros(p[:, 1].shape)]).T, 1)
        dz = np.amax(np.vstack([boxMin[2] - p[:, 2], p[:, 2] - boxMax[2], np.zeros(p[:, 2].shape)]).T, 1)

        # convert to distance
        distances = np.vstack([dx, dy, dz]).T
        dist = np.linalg.norm(distances, axis=1)

        # Figure out the signs
        signs = np.sign(boxCenter-p)

        # Calculate unit vector and replace with
        unit = distances / dist[:, np.newaxis] * signs
        unit[np.isnan(unit)] = 0
        unit[np.isinf(unit)] = 0
        return dist, unit

    @staticmethod
    def compute_forces(target, map_struct, current):
        """
        Helper function for the computation of forces on every joints. Computes the sum
        of forces (attactive, repulsive) on each joint.

        INPUTS:
        target - 3x7 numpy array representing the desired joint/end effector positions
        in the world frame
        obstacle - nx6 numpy array representing the obstacle box min and max positions
        in the world frame
        current- 3x7 numpy array representing the current joint/end effector positions
        in the world frame

        OUTPUTS:
        joint_forces - 3x7 numpy array representing the force vectors on each
        joint/end effector
        """

        ## STUDENT CODE STARTS HERE

        joint_forces = np.zeros((3, 7))
        att_forces = np.zeros((3, 7))
        rep_forces = np.zeros((3, 7))

        for i in range(7):
          #attractive force for this joint to goal
          #attarctive_force(target - 3x1, current - 3x1) = output - 3x1
          att_forces[:,i] = (PotentialFieldPlanner.attractive_force(target[:,i], current[:,i])).flatten() #1x3 transposed to 3x1
          list_rep_forces = np.array([])
          count = 0
          for j in map_struct.obstacles:
            #repulsive forces for each obstacle for this joint
            #repulsive_force(obstacle - 1x6, current - 3x1, unitvec - 3x1) = output - 3x1
            # list_rep_forces[count] =
            rf = PotentialFieldPlanner.repulsive_force(j, current[:,i]).flatten() #3x1
            count+=1
            rep_forces[:,i] += rf
            # rep_forces[i] = list_rep_forces
          ##sum all repulsive forces

          # print('att forces shape', att_forces.shape)
          # print('rep forces shape', rep_forces.shape)
          # print('listrep forces shape', list_rep_forces.shape)

          # rep_forces[:,i] s= np.sum(list_rep_forces, axis = 0)

        # for i in range(0, len(current_pos.shape[0])-1):
        #   joint_forces[i] = att_forces[i] + rep_forces[i]

        joint_forces = att_forces + rep_forces

        joint_forces.reshape(3,7)
        ## END STUDENT CODE

        return joint_forces

    @staticmethod
    def compute_torques(joint_forces, q):
        """
        Helper function for converting joint forces to joint torques. Computes the sum
        of torques on each joint.

        INPUTS:
        joint_forces - 3x7 numpy array representing the force vectors on each
        joint/end effector
        q - 1x7 numpy array representing the current joint angles

        OUTPUTS:
        joint_torques - 1x7 numpy array representing the torques on each joint
        """

        ## STUDENT CODE STARTS HERE

        joint_torques = np.zeros((1, 7))
        torque = np.zeros((7, 7))

        J = calcJacobian(q)[:-3, :] #3x7 linear vels
        J = J.T
        J1 = np.array([[J[0][0],0,0,0,0,0,0],
                       [J[0][1],0,0,0,0,0,0],
                       [J[0][2],0,0,0,0,0,0]])
        J2 = np.array([[J[0][0],J[1][0],0,0,0,0,0],
                       [J[0][1],J[1][1],0,0,0,0,0],
                       [J[0][2],J[1][2],0,0,0,0,0]])
        J3 = np.array([[J[0][0],J[1][0],J[2][0],0,0,0,0],
                       [J[0][1],J[1][1],J[2][1],0,0,0,0],
                       [J[0][2],J[1][2],J[2][2],0,0,0,0]])
        J4 = np.array([[J[0][0],J[1][0],J[2][0],J[3][0],0,0,0],
                       [J[0][1],J[1][1],J[2][1],J[3][1],0,0,0],
                       [J[0][2],J[1][2],J[2][2],J[3][2],0,0,0]])
        J5 = np.array([[J[0][0],J[1][0],J[2][0],J[3][0],J[4][0],0,0],
                       [J[0][1],J[1][1],J[2][1],J[3][1],J[4][1],0,0],
                       [J[0][2],J[1][2],J[2][2],J[3][2],J[4][2],0,0]])
        J6 = np.array([[J[0][0],J[1][0],J[2][0],J[3][0],J[4][0],J[5][0],0],
                       [J[0][1],J[1][1],J[2][1],J[3][1],J[4][1],J[5][1],0],
                       [J[0][2],J[1][2],J[2][2],J[3][2],J[4][2],J[5][2],0]])
        J7 = np.array([[J[0][0],J[1][0],J[2][0],J[3][0],J[4][0],J[5][0],J[6][0]],
                       [J[0][1],J[1][1],J[2][1],J[3][1],J[4][1],J[5][1],J[6][1]],
                       [J[0][2],J[1][2],J[2][2],J[3][2],J[4][2],J[5][2],J[6][2]]])

        J_list = [J1, J2, J3, J4, J5, J6, J7]
        for i in range(len(J_list)):
          torque[:,i] = J_list[i].T @ joint_forces[:,i] #7x3 @ 3x1 = 7x1

        joint_torques = np.sum(torque, axis = 0)
        joint_torques = joint_torques.reshape(1,7)

        ## END STUDENT CODE

        return joint_torques

    @staticmethod
    def q_distance(target, current):
        """
        Helper function which computes the distance between any two
        vectors.

        This data can be used to decide whether two joint sets can be
        considered equal within a certain tolerance.

        INPUTS:
        target - 1x7 numpy array representing some joint angles
        current - 1x7 numpy array representing some joint angles

        OUTPUTS:
        distance - the distance between the target and the current joint sets

        """

        ## STUDENT CODE STARTS HERE

        distance = 0

        ## END STUDENT CODE

        return distance

    @staticmethod
    def compute_gradient(q, target, map_struct):
        """
        Computes the joint gradient step to move the current joint positions to the
        next set of joint positions which leads to a closer configuration to the goal
        configuration

        INPUTS:
        q - 1x7 numpy array. the current joint configuration, a "best guess" so far for the final answer
        target - 1x7 numpy array containing the desired joint angles
        map_struct - a map struct containing the obstacle box min and max positions

        OUTPUTS:
        dq - 1x7 numpy array. a desired joint velocity to perform this task
        """

        ## STUDENT CODE STARTS HERE

        dq = np.zeros((1, 7))
        # print('TARGET', target.shape)
        target = target.reshape(7,1)
        # print('TARGET NEW', target.shape)
        target_position, __ = PotentialFieldPlanner.fk.forward(target)
        target_pos = target_position[:-1].T
        current_position, __ = PotentialFieldPlanner.fk.forward(q)
        current_pos = current_position[:-1].T

        #computeforces(target - 3x7, obstacle - nx6, current - 3x7) = output - 3x7
        total_forces = PotentialFieldPlanner.compute_forces(target_pos, map_struct, current_pos)

        #computetorques(forces - 3x7, q_current - 1x7) = output - 1x7
        total_torques = PotentialFieldPlanner.compute_torques(total_forces, q)

        a = 0.03
        dq = a * total_torques / np.linalg.norm(total_torques)

        ## END STUDENT CODE

        return dq

    ###############################
    ### Potential Feild Solver  ###
    ###############################

    def plan(self, map_struct, start, goal):
        """
        Uses potential field to move the Panda robot arm from the startng configuration to
        the goal configuration.

        INPUTS:
        map_struct - a map struct containing min and max positions of obstacle boxes
        start - 1x7 numpy array representing the starting joint angles for a configuration
        goal - 1x7 numpy array representing the desired joint angles for a configuration

        OUTPUTS:
        q - nx7 numpy array of joint angles [q0, q1, q2, q3, q4, q5, q6]. This should contain
        all the joint angles throughout the path of the planner. The first row of q should be
        the starting joint angles and the last row of q should be the goal joint angles.
        """

        q_path = np.array([]).reshape(0,7)
        # goal_pos = FK(goal) #8x3
        q_path = np.array([start])

        step_count = 0

        while step_count <= self.max_steps:
            step_count+=1

            ## STUDENT CODE STARTS HERE

            # The following comments are hints to help you to implement the planner
            # You don't necessarily have to follow these steps to complete your code

            # Compute gradient
            # TODO: this is how to change your joint angles
            #computegradient(q - 1x7, target - 1x7, map_struct) = output 1x7

            q_next = q_path[-1] + PotentialFieldPlanner.compute_gradient(q_path[-1], goal, map_struct)


            #Termination Conditions

            #if at goal, break
            dist_to_goal = np.mean(abs(goal - q_next))

            if dist_to_goal < self.tol:
                #update q path
                q_path = np.vstack((q_path, q_next))
                break

            #if collision, break
            # j1 = q_next[:7]
            # j2 = q_next[1:8]
            # print(j1, j2)
            # for j in map_struct.obstacles:
            # 
            #   ifCollide = detectCollision(j1, j2, j)
            #   print("IF COLLIDE", ifCollide)
            #   if ifCollide:
            #     break  #exit the while loop if conditions are met!

            dist_between_joints = np.mean(abs(q_next - q_path[-1]))
            if dist_between_joints < self.min_step_size:
              q_path = np.vstack((q_path,q_next))
              break

            q_path = np.vstack((q_path,q_next))

            # c = 0.5 #parameter
            # ##update steps
            # for i in range(0, len(current_pos.shape[0])-1):
            #   curr_pos[joint] += torques[joint]*c

            # q_path.append(current_position)

            # Termination Conditions





            # YOU NEED TO CHECK FOR COLLISIONS WITH OBSTACLES
            # TODO: Figure out how to use the provided function

            # YOU MAY NEED TO DEAL WITH LOCAL MINIMA HERE
            # TODO: when detect a local minima, implement a random walk

            ## END STUDENT CODE

        return q_path

################################
## Simple Testing Environment ##
################################

if __name__ == "__main__":

    np.set_printoptions(suppress=True,precision=5)

    planner = PotentialFieldPlanner()

    # inputs
    map_struct = loadmap("../maps/map1.txt")
    start = np.array([0,-1,0,-2,0,1.57,0])
    goal =  np.array([-1.2, 1.57 , 1.57, -2.07, -1.57, 1.57, 0.7])

    # potential field planning
    q_path = planner.plan(deepcopy(map_struct), deepcopy(start), deepcopy(goal))

    # show results
    for i in range(q_path.shape[0]):
        error = PotentialFieldPlanner.q_distance(q, goal)
        print('iteration:',i,' q =', q_path[i, :], ' error={error:3.4f}'.format(error=error))

    print("q path: ", q_path)